### ISSUE TITLE
How to attach key signature changes?

### ISSUE THREAD

**Issue by madskjeldgaard** [n-armstrong/fosc#5]
Hi!

Thanks so much for making this package. It is really incredibly nicely made!

One thing I haven't figured out yet is how to attach a Key Signature in a voice, like this abjad thing:
https://abjad.github.io/api/abjad/indicators.html#abjad.indicators.KeySignature

I would expect something that works sort of like meters, but I can't find any info on any Key Signature stuff in the package.

```supercollider
// Set new time signature
voice[0].attach(FoscTimeSignature(FoscMeter(meter)));
```

Thanks and keep up the amazing work

**Comment by n-armstrong** [comment]
Hi,

Thanks for the comments about Fosc!

I was surprised to see that I've never added a KeySignature class, but it was an easy one to make and it's now included in the repository. The usage is as you'd expect:

a = FoscVoice([FoscNote(64, 1/4)]);
a[0].attach(FoscKeySignature("e", "major"));
a.show;

cheers
Newton

**Comment by madskjeldgaard** [comment]
Wow, that was fast! Thanks, this works perfectly.
